# Imports and Reads

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv('kc_house_data.csv')

In [3]:
df.head()

id        date     price  bedrooms  bathrooms  sqft_living  \
0  7129300520  10/13/2014  221900.0         3       1.00         1180   
1  6414100192   12/9/2014  538000.0         3       2.25         2570   
2  5631500400   2/25/2015  180000.0         2       1.00          770   
3  2487200875   12/9/2014  604000.0         4       3.00         1960   
4  1954400510   2/18/2015  510000.0         3       2.00         1680   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0         NaN   0.0  ...      7        1180            0.0   
1      7242     2.0         0.0   0.0  ...      7        2170          400.0   
2     10000     1.0         0.0   0.0  ...      6         770            0.0   
3      5000     1.0         0.0   0.0  ...      7        1050          910.0   
4      8080     1.0         0.0   0.0  ...      8        1680            0.0   

  yr_built  yr_renovated  zipcode      lat     long  sqft_living15  sqft_lot15  
0     1955           0.0    98178  47.5112 -122.257           1340        5650  
1     1951        1991.0    98125  47.7210 -122.319           1690        7639  
2     1933           NaN    98028  47.7379 -122.233           2720        8062  
3     1965           0.0    98136  47.5208 -122.393           1360        5000  
4     1987           0.0    98074  47.6168 -122.045           1800        7503  

[5 rows x 21 columns]

In [4]:
df.describe()

id         price      bedrooms     bathrooms   sqft_living  \
count  2.159700e+04  2.159700e+04  21597.000000  21597.000000  21597.000000   
mean   4.580474e+09  5.402966e+05      3.373200      2.115826   2080.321850   
std    2.876736e+09  3.673681e+05      0.926299      0.768984    918.106125   
min    1.000102e+06  7.800000e+04      1.000000      0.500000    370.000000   
25%    2.123049e+09  3.220000e+05      3.000000      1.750000   1430.000000   
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  7.700000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront          view     condition  \
count  2.159700e+04  21597.000000  19221.000000  21534.000000  21597.000000   
mean   1.509941e+04      1.494096      0.007596      0.233863      3.409825   
std    4.141264e+04      0.539683      0.086825      0.765686      0.650546   
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000   
50%    7.618000e+03      1.500000      0.000000      0.000000      3.000000   
75%    1.068500e+04      2.000000      0.000000      0.000000      4.000000   
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000   

              grade    sqft_above      yr_built  yr_renovated       zipcode  \
count  21597.000000  21597.000000  21597.000000  17755.000000  21597.000000   
mean       7.657915   1788.596842   1970.999676     83.636778  98077.951845   
std        1.173200    827.759761     29.375234    399.946414     53.513072   
min        3.000000    370.000000   1900.000000      0.000000  98001.000000   
25%        7.000000   1190.000000   1951.000000      0.000000  98033.000000   
50%        7.000000   1560.000000   1975.000000      0.000000  98065.000000   
75%        8.000000   2210.000000   1997.000000      0.000000  98118.000000   
max       13.000000   9410.000000   2015.000000   2015.000000  98199.000000   

                lat          long  sqft_living15     sqft_lot15  
count  21597.000000  21597.000000   21597.000000   21597.000000  
mean      47.560093   -122.213982    1986.620318   12758.283512  
std        0.138552      0.140724     685.230472   27274.441950  
min       47.155900   -122.519000     399.000000     651.000000  
25%       47.471100   -122.328000    1490.000000    5100.000000  
50%       47.571800   -122.231000    1840.000000    7620.000000  
75%       47.678000   -122.125000    2360.000000   10083.000000  
max       47.777600   -121.315000    6210.000000  871200.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 21 columns):
id               21597 non-null int64
date             21597 non-null object
price            21597 non-null float64
bedrooms         21597 non-null int64
bathrooms        21597 non-null float64
sqft_living      21597 non-null int64
sqft_lot         21597 non-null int64
floors           21597 non-null float64
waterfront       19221 non-null float64
view             21534 non-null float64
condition        21597 non-null int64
grade            21597 non-null int64
sqft_above       21597 non-null int64
sqft_basement    21597 non-null object
yr_built         21597 non-null int64
yr_renovated     17755 non-null float64
zipcode          21597 non-null int64
lat              21597 non-null float64
long             21597 non-null float64
sqft_living15    21597 non-null int64
sqft_lot15       21597 non-null int64
dtypes: float64(8), int64(11), object(2)
memory usage: 3.5+ MB


In [6]:
df.isna().sum()

id                  0
date                0
price               0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2376
view               63
condition           0
grade               0
sqft_above          0
sqft_basement       0
yr_built            0
yr_renovated     3842
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [7]:
df.waterfront.unique()

array([nan,  0.,  1.])

Fill in waterfront later using a lat and long 

In [8]:
df.yr_renovated.unique()

array([   0., 1991.,   nan, 2002., 2010., 1992., 2013., 1994., 1978.,
       2005., 2003., 1984., 1954., 2014., 2011., 1983., 1945., 1990.,
       1988., 1977., 1981., 1995., 2000., 1999., 1998., 1970., 1989.,
       2004., 1986., 2007., 1987., 2006., 1985., 2001., 1980., 1971.,
       1979., 1997., 1950., 1969., 1948., 2009., 2015., 1974., 2008.,
       1968., 2012., 1963., 1951., 1962., 1953., 1993., 1996., 1955.,
       1982., 1956., 1940., 1976., 1946., 1975., 1964., 1973., 1957.,
       1959., 1960., 1967., 1965., 1934., 1972., 1944., 1958.])

In [9]:
df.yr_renovated.value_counts()

0.0       17011
2014.0       73
2003.0       31
2013.0       31
2007.0       30
          ...  
1946.0        1
1959.0        1
1971.0        1
1951.0        1
1954.0        1
Name: yr_renovated, Length: 70, dtype: int64

make unrenovated houses into categorical (Old house and New house). bin all old houses

In [10]:
df.view.unique()

array([ 0., nan,  3.,  4.,  2.,  1.])

In [11]:
df.view.value_counts()

0.0    19422
2.0      957
3.0      508
1.0      330
4.0      317
Name: view, dtype: int64

change view to categorical. 0 to no view

In [12]:
df[df.bedrooms == 33] 
df[df.bedrooms == 11]
df[df.bedrooms == 10]
df[df.bedrooms > 5]

id        date      price  bedrooms  bathrooms  sqft_living  \
209    6300000550   7/17/2014   464000.0         6       3.00         2300   
232    9264902050  11/21/2014   315000.0         6       2.75         2940   
239    5152100060   5/29/2014   472000.0         6       2.50         4410   
331    2946001550   4/16/2015   279000.0         6       1.75         2240   
486    9286000240   7/11/2014  1070000.0         6       3.50         4860   
...           ...         ...        ...       ...        ...          ...   
20968  2149800278  10/15/2014   343000.0         6       5.00         2732   
21069  4449800480   3/18/2015   677790.0         6       3.00         2800   
21170  7896300592   1/14/2015   303500.0         6       4.50         3390   
21359  6061500100   7/17/2014  1170000.0         6       3.50         4310   
21506   603000555    3/2/2015   462500.0         6       3.00         2390   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
209        3404     2.0         0.0   0.0  ...      7        1600   
232        7350     1.0         0.0   0.0  ...      8        1780   
239       14034     1.0         0.0   2.0  ...      9        2350   
331       11180     2.0         0.0   0.0  ...      7        2240   
486       11793     2.0         0.0   0.0  ...     11        3860   
...         ...     ...         ...   ...  ...    ...         ...   
20968      7655     2.0         0.0   0.0  ...      7        2732   
21069      4213     2.0         NaN   0.0  ...      8        2800   
21170      7200     2.0         0.0   0.0  ...      8        2440   
21359      7760     2.0         0.0   0.0  ...     10        3260   
21506      4000     2.0         0.0   0.0  ...      7        2390   

       sqft_basement yr_built  yr_renovated  zipcode      lat     long  \
209            700.0     1920        1994.0    98133  47.7067 -122.343   
232           1160.0     1978           0.0    98023  47.3103 -122.339   
239           2060.0     1965           0.0    98003  47.3376 -122.324   
331              0.0     1955           0.0    98198  47.4200 -122.323   
486           1000.0     1998           0.0    98006  47.5521 -122.137   
...              ...      ...           ...      ...      ...      ...   
20968            0.0     2009           0.0    98002  47.3045 -122.211   
21069            0.0     1998           0.0    98117  47.6892 -122.389   
21170          950.0     2007           0.0    98118  47.5205 -122.288   
21359         1050.0     2013           0.0    98059  47.5297 -122.155   
21506            0.0     2014           0.0    98118  47.5173 -122.286   

       sqft_living15  sqft_lot15  
209             1560        1312  
232             2120        8236  
239             2600       13988  
331             1590        7955  
486             3600       11793  
...              ...         ...  
20968           3078       69993  
21069           1440        3960  
21170           2040        7214  
21359           4620       10217  
21506           1680        5000  

[334 rows x 21 columns]

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 21 columns):
id               21597 non-null int64
date             21597 non-null object
price            21597 non-null float64
bedrooms         21597 non-null int64
bathrooms        21597 non-null float64
sqft_living      21597 non-null int64
sqft_lot         21597 non-null int64
floors           21597 non-null float64
waterfront       19221 non-null float64
view             21534 non-null float64
condition        21597 non-null int64
grade            21597 non-null int64
sqft_above       21597 non-null int64
sqft_basement    21597 non-null object
yr_built         21597 non-null int64
yr_renovated     17755 non-null float64
zipcode          21597 non-null int64
lat              21597 non-null float64
long             21597 non-null float64
sqft_living15    21597 non-null int64
sqft_lot15       21597 non-null int64
dtypes: float64(8), int64(11), object(2)
memory usage: 3.5+ MB


## Classifying features as categoricals, strings and numeric

In [14]:
categoricals = []
numeric = []
strings = []

split = 10


for col in list(df.columns):
    if df[col].dtype == 'int64' or df[col].dtype == 'float64':
        if len(df[col].unique()) < split:
            categoricals.append(col)
        else:
            numeric.append(col)
    else:
        if len(df[col].unique()) < split:
            categoricals.append(col)
        else:
            strings.append(col)
            
print('Categoricals:', categoricals)
print('Numeric:', numeric)
print('Strings:', strings)

Categoricals: ['floors', 'waterfront', 'view', 'condition']
Numeric: ['id', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'grade', 'sqft_above', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15']
Strings: ['date', 'sqft_basement']


Maybe drop dates. but before that convert them to date time and plot prices vs date

In [15]:
df.date = pd.to_datetime(df.date)

In [16]:
df.date.sort_values()

7316    2014-05-02
20586   2014-05-02
1040    2014-05-02
20543   2014-05-02
9587    2014-05-02
           ...    
19381   2015-05-14
12623   2015-05-14
5632    2015-05-15
13040   2015-05-24
16580   2015-05-27
Name: date, Length: 21597, dtype: datetime64[ns]

no real variation with time so date can be dropped

In [17]:
# sns.set_style('ticks')
# sns.scatterplot(df.bedrooms, df.price, hue = df.floors, alpha = 0.8)

In [18]:
print('Categoricals:', categoricals)
print('Numeric:', numeric)
print('Strings:', strings)

Categoricals: ['floors', 'waterfront', 'view', 'condition']
Numeric: ['id', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'grade', 'sqft_above', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15']
Strings: ['date', 'sqft_basement']


# Notes so far

## Categoricals

* floors can be numeric as they indicate some numeric quantity. 
* waterfront needs to be filled in using map data.
* view should be numeric. the nans should be filled in with the median or mode. only 63 missing values.
* condition should be treated as numeric. data is complete.

## Numeric

* id should be dropped
* price should be set as target
* rows with bedrooms above 5 are dropped 
* bathrooms are ok
* squarefeet columns are ok
* grade is ok
* yr_built is ok
* yr_renovated could be binned, (renovated or not), bin the ones that are renovated based on how recent the renovation was.
* keep coordinates and zipcode
* drop date

(also try drop zipcode, keep zipcode along with id)


In [19]:
df.corr()

id     price  bedrooms  bathrooms  sqft_living  sqft_lot  \
id             1.000000 -0.016772  0.001150   0.005162    -0.012241 -0.131911   
price         -0.016772  1.000000  0.308787   0.525906     0.701917  0.089876   
bedrooms       0.001150  0.308787  1.000000   0.514508     0.578212  0.032471   
bathrooms      0.005162  0.525906  0.514508   1.000000     0.755758  0.088373   
sqft_living   -0.012241  0.701917  0.578212   0.755758     1.000000  0.173453   
sqft_lot      -0.131911  0.089876  0.032471   0.088373     0.173453  1.000000   
floors         0.018608  0.256804  0.177944   0.502582     0.353953 -0.004814   
waterfront    -0.004176  0.276295 -0.002386   0.067282     0.110230  0.023143   
view           0.011592  0.395734  0.078523   0.186451     0.282532  0.075298   
condition     -0.023803  0.036056  0.026496  -0.126479    -0.059445 -0.008830   
grade          0.008188  0.667951  0.356563   0.665838     0.762779  0.114731   
sqft_above    -0.010799  0.605368  0.479386   0.686668     0.876448  0.184139   
yr_built       0.021617  0.053953  0.155670   0.507173     0.318152  0.052946   
yr_renovated  -0.012010  0.129599  0.018495   0.051050     0.055660  0.004513   
zipcode       -0.008211 -0.053402 -0.154092  -0.204786    -0.199802 -0.129586   
lat           -0.001798  0.306692 -0.009951   0.024280     0.052155 -0.085514   
long           0.020672  0.022036  0.132054   0.224903     0.241214  0.230227   
sqft_living15 -0.002701  0.585241  0.393406   0.569884     0.756402  0.144763   
sqft_lot15    -0.138557  0.082845  0.030690   0.088303     0.184342  0.718204   

                 floors  waterfront      view  condition     grade  \
id             0.018608   -0.004176  0.011592  -0.023803  0.008188   
price          0.256804    0.276295  0.395734   0.036056  0.667951   
bedrooms       0.177944   -0.002386  0.078523   0.026496  0.356563   
bathrooms      0.502582    0.067282  0.186451  -0.126479  0.665838   
sqft_living    0.353953    0.110230  0.282532  -0.059445  0.762779   
sqft_lot      -0.004814    0.023143  0.075298  -0.008830  0.114731   
floors         1.000000    0.021883  0.028436  -0.264075  0.458794   
waterfront     0.021883    1.000000  0.406654   0.017642  0.087383   
view           0.028436    0.406654  1.000000   0.045735  0.249727   
condition     -0.264075    0.017642  0.045735   1.000000 -0.146896   
grade          0.458794    0.087383  0.249727  -0.146896  1.000000   
sqft_above     0.523989    0.075463  0.166299  -0.158904  0.756073   
yr_built       0.489193   -0.026079 -0.054564  -0.361592  0.447865   
yr_renovated   0.003535    0.087244  0.100964  -0.061858  0.016669   
zipcode       -0.059541    0.031057  0.085277   0.002888 -0.185771   
lat            0.049239   -0.012772  0.006141  -0.015102  0.113575   
long           0.125943   -0.039864 -0.077894  -0.105877  0.200341   
sqft_living15  0.280102    0.088860  0.279561  -0.093072  0.713867   
sqft_lot15    -0.010722    0.032002  0.073332  -0.003126  0.120981   

               sqft_above  yr_built  yr_renovated   zipcode       lat  \
id              -0.010799  0.021617     -0.012010 -0.008211 -0.001798   
price            0.605368  0.053953      0.129599 -0.053402  0.306692   
bedrooms         0.479386  0.155670      0.018495 -0.154092 -0.009951   
bathrooms        0.686668  0.507173      0.051050 -0.204786  0.024280   
sqft_living      0.876448  0.318152      0.055660 -0.199802  0.052155   
sqft_lot         0.184139  0.052946      0.004513 -0.129586 -0.085514   
floors           0.523989  0.489193      0.003535 -0.059541  0.049239   
waterfront       0.075463 -0.026079      0.087244  0.031057 -0.012772   
view             0.166299 -0.054564      0.100964  0.085277  0.006141   
condition       -0.158904 -0.361592     -0.061858  0.002888 -0.015102   
grade            0.756073  0.447865      0.016669 -0.185771  0.113575   
sqft_above       1.000000  0.424037      0.022137 -0.261570 -0.001199   
yr_built         0.424037  1.000000     -0.225209 

In [20]:
# sns.heatmap(df.corr().abs())

# Cleanup Process


* floors are ok 
* waterfront needs to be filled in using map data.
* view need to be filled. the nans should be filled in with the median or mode. only 63 missing values.
* condition is ok

* id should be dropped
* price should be set as target
* rows with bedrooms above 5 are dropped 
* bathrooms are ok
* squarefeet columns are ok
* grade is ok
* yr_built is ok
* yr_renovated could be binned, (renovated or not), bin the ones that are renovated based on how recent the renovation was.
* keep coordinates and zipcode
* drop date

In [21]:
list(df.columns)

['id',
 'date',
 'price',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

In [22]:
to_drop = ['id', 'date']

### filling in view

In [23]:
idx = df['view'].isna()

In [24]:
df.view.median()

0.0

In [25]:
df[idx] = df.view.median()

In [26]:
df.view.isna().sum()

0

### dropping houses above 5 bedrooms

In [27]:
idx = df[df.bedrooms > 5]

In [28]:
df = df.drop(idx.index)

In [29]:
len(df)

21265

In [30]:
df.bedrooms.isna().sum()

0

### binning year renovated

In [31]:
df.isna().sum()

id                  0
date                0
price               0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2320
view                0
condition           0
grade               0
sqft_above          0
sqft_basement       0
yr_built            0
yr_renovated     3778
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [32]:
idx = df.yr_renovated.isna()

In [33]:
np.sort(df[idx].yr_built.unique())

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920., 1921., 1922., 1923., 1924., 1925., 1926.,
       1927., 1928., 1929., 1930., 1931., 1932., 1933., 1934., 1935.,
       1936., 1937., 1938., 1939., 1940., 1941., 1942., 1943., 1944.,
       1945., 1946., 1947., 1948., 1949., 1950., 1951., 1952., 1953.,
       1954., 1955., 1956., 1957., 1958., 1959., 1960., 1961., 1962.,
       1963., 1964., 1965., 1966., 1967., 1968., 1969., 1970., 1971.,
       1972., 1973., 1974., 1975., 1976., 1977., 1978., 1979., 1980.,
       1981., 1982., 1983., 1984., 1985., 1986., 1987., 1988., 1989.,
       1990., 1991., 1992., 1993., 1994., 1995., 1996., 1997., 1998.,
       1999., 2000., 2001., 2002., 2003., 2004., 2005., 2006., 2007.,
       2008., 2009., 2010., 2011., 2012., 2013., 2014., 2015.])

In [34]:
df[idx].yr_renovated = 0

/Users/dylanlisk/opt/anaconda3/envs/learn-env/lib/python3.6/site-packages/pandas/core/generic.py:5208: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


In [35]:
df.loc[idx, 'yr_renovated']  = 0

In [36]:
df.isna().sum()

id                  0
date                0
price               0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2320
view                0
condition           0
grade               0
sqft_above          0
sqft_basement       0
yr_built            0
yr_renovated        0
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [37]:
idx = df.yr_renovated != 0

In [38]:
idx

0        False
1         True
2        False
3        False
4        False
         ...  
21592    False
21593    False
21594    False
21595    False
21596    False
Name: yr_renovated, Length: 21265, dtype: bool

In [39]:
sum(idx)

716

In [40]:
df[idx].yr_renovated

1        1991.0
35       2002.0
95       1991.0
103      2010.0
125      1992.0
          ...  
19602    2004.0
20041    2006.0
20428    2009.0
20431    2014.0
20946    2007.0
Name: yr_renovated, Length: 716, dtype: float64

In [41]:
df[idx].yr_renovated.describe()

count     716.000000
mean     1995.937151
std        15.706494
min      1934.000000
25%      1987.000000
50%      2000.000000
75%      2008.000000
max      2015.000000
Name: yr_renovated, dtype: float64

In [42]:
pd.qcut(df[idx].yr_renovated, 5, range(1,6)).astype(int)

1        2
35       3
95       2
103      4
125      2
        ..
19602    4
20041    4
20428    4
20431    5
20946    4
Name: yr_renovated, Length: 716, dtype: int64

In [43]:
df.loc[idx, 'yr_renovated'] = pd.qcut(df[idx].yr_renovated, 5, range(1,6)).astype(int)

In [44]:
df.yr_renovated.value_counts()

0.0    20549
2.0      151
4.0      146
1.0      145
3.0      142
5.0      132
Name: yr_renovated, dtype: int64

In [45]:
df.head()

id                 date     price  bedrooms  bathrooms  \
0  7.129301e+09  2014-10-13 00:00:00  221900.0       3.0       1.00   
1  6.414100e+09  2014-12-09 00:00:00  538000.0       3.0       2.25   
2  5.631500e+09  2015-02-25 00:00:00  180000.0       2.0       1.00   
3  2.487201e+09  2014-12-09 00:00:00  604000.0       4.0       3.00   
4  1.954401e+09  2015-02-18 00:00:00  510000.0       3.0       2.00   

   sqft_living  sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
0       1180.0    5650.0     1.0         NaN   0.0  ...    7.0      1180.0   
1       2570.0    7242.0     2.0         0.0   0.0  ...    7.0      2170.0   
2        770.0   10000.0     1.0         0.0   0.0  ...    6.0       770.0   
3       1960.0    5000.0     1.0         0.0   0.0  ...    7.0      1050.0   
4       1680.0    8080.0     1.0         0.0   0.0  ...    8.0      1680.0   

   sqft_basement yr_built  yr_renovated  zipcode      lat     long  \
0            0.0   1955.0           0.0  98178.0  47.5112 -122.257   
1          400.0   1951.0           2.0  98125.0  47.7210 -122.319   
2            0.0   1933.0           0.0  98028.0  47.7379 -122.233   
3          910.0   1965.0           0.0  98136.0  47.5208 -122.393   
4            0.0   1987.0           0.0  98074.0  47.6168 -122.045   

   sqft_living15  sqft_lot15  
0         1340.0      5650.0  
1         1690.0      7639.0  
2         2720.0      8062.0  
3         1360.0      5000.0  
4         1800.0      7503.0  

[5 rows x 21 columns]

In [46]:
df.to_csv('Cleaned_Housing_Data_v1.csv')


Untouched
     floors, condition, bathrooms, all squarefeet columns, grade, yr_built, coordinates, zipcode.
     
Dropped
    id, date

Processed
   * view nans filled with median (63 missing values). 
   * rows with bedrooms greater than 5 are dropped (about 300 rows out of 21k so our model could be more accurate)
   * yr_renovated had zeros, nans and years. nans have been set to 0. all the years are binned in equal numbers from 1 to 5. So yr_renovated is now a scale from 0 to 5, 0 being not renovated and 5 being recently renovated.
   
Still needs processing
    waterfront - has a bunch of nans. could be filled in using map data, but still need to figure out how.
    
If i missed any over here assume they are untouched :)


In [47]:
from sklearn.cluster import DBSCAN

In [59]:
lat_long = df[['lat','long']].to_numpy()

In [100]:
clustering = DBSCAN(eps=.036).fit(lat_long)


In [101]:
clustering.labels_

array([0, 0, 0, ..., 0, 0, 0])

In [102]:
unique, counts = np.unique(clustering.labels_, return_counts=True)
print(np.asarray((unique, counts)).T)

[[   -1    10]
 [    0 21064]
 [    1    63]
 [    2   117]
 [    3    11]]
